name: GitHub Action Submodule Network
description: Automatically updates the app of each subsidiary when the core is updated
author: Juan David Argüello Plata, jdarguello

branding:
  icon: 'Briefcase'
  color: 'blue'

inputs:
  subsidiary_repo_url:
    description: 'GitHub: owner/repo  -  Azure: <azure_domain>/repo '
    required: true
  subsidiary_token:
    description: token (from GitHub or Azure) to update the submodule
    required: true
  subsidiary_repo_name:
    description: (optional) only for Azure Repos. It is the name of the repository
    required: false
  subsidiary_repo_username:
    description: (Only required for Azure Repos) username for the checkout process
    required: false
    default: ''
  platform:
    description: either 'GitHub' or 'Azure'
    required: false
    default: GitHub
  operation:
    description: either 'push' or 'pull-request' operations
    required: false
    default: push
  subsidiary_branch:
    description: branch of the submodule
    required: false
    default: main
  parent_branch:
    required: false
    default: main
  default_message:
    required: false
    default: 'bancolombia-dependabot: updating submodules'
  

runs:
  using: 'composite'
  steps:
    - name: Update subsidiary - GitHub
      if: inputs.platform == 'GitHub'
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.subsidiary_token }}
        repository: ${{ inputs.subsidiary_repo_url }}
        ref: ${{ inputs.branch }}
        submodules: true
        fetch-depth: 0
    - name: Checkout subsidiary - Azure
      if: inputs.platform == 'Azure'
      uses: bancolombia/checkout-azure-repo@v1
      with: 
        token: ${{ inputs.subsidiary_token }}
        username: ${{ inputs.subsidiary_repo_name }}
        repo_url: ${{ inputs.subsidiary_repo_url }}
    - name: List local directories
      shell:  bash
      run: ls -la
    - name: Create new commit and push changes
      if: inputs.operation == 'push'
      working-directory: ./${{ inputs.subsidiary_repo_name }}
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git submodule update --remote
        git commit -am "${{ inputs.default_message }}"
        git push
    #- name: Create new pull request
    #  if: inputs.operation == 'pull-request'
    #  working-directory: ./${{ inputs.subsidiary_repo_name }}
    #  uses: peter-evans/create-pull-request@v3
    # with:
    #      token: ${{ inputs.subsidiary_token }}
    #      commit-message: ${{ inputs.default_message }}
    #      title: Automatic Pull Request
    #      body: ${{ inputs.default_message }}